import { Component } from '@angular/core';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.css'
})
export class ProductListComponent {


// Dummy products array
Product = [
  
{
  id: 1,
  name: 'Product 1',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: true,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-1',
  },
{
  id: 2,
  name: 'Product 2',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: false,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-2',
  },
{
  id: 3,
  name: 'Product 3',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: true,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-3',
  },
{
  id: 4,
  name: 'Product 4',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: false,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-4',
  },
{
  id: 5,
  name: 'Product 5',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: true,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-5',
  },
{
  id: 6,
  name: 'Product 6',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: false,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-6',
  },
{
  id: 7,
  name: 'Product 7',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: true,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-7',
  },
{
  id: 8,
  name: 'Product 8',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: false,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-8',
  },
{
  id: 9,
  name: 'Product 9',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  is_in_inventory: true,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-9',
  },
{
  id: 10,
  name: 'Product 10',
  description: 'Description for Product 3',
  brand: 'Brand C',
  gender: 'Unisex',
  category: 'Accessories',
  size: 'One Size',
  color: ['Black', 'Red', 'Yellow', 'Green'],
  price: 19.99,
  discount:10,
  is_in_inventory: false,
  items_left: 0,
  imageURL: '../../assets/images/shoes.png',
  slug: 'product-10',
  },
];


}
